import { readFileSync } from "node:fs";
import { CANONICAL_V1_VERSION, type CanonicalClient } from "../../src/domain/client.js";

export function fixture(name: "acorn-client" | "beacon-client" | "cosper-client-request"): unknown {
  const data: unknown = JSON.parse(
    readFileSync(new URL(`../../fixtures/${name}.json`, import.meta.url), "utf8"),
  );
  return data;
}

export function deepFreeze(value: unknown): void {
  if (value !== null && typeof value === "object") {
    Object.freeze(value);
    for (const nested of Object.values(value)) deepFreeze(nested);
  }
}

/** Hand-authored expectations, not generated by a production mapping function. */
export function expectedAcorn(): CanonicalClient {
  return {
    schema_version: CANONICAL_V1_VERSION,
    id: "90210",
    title: "Mrs",
    first_name: "Priya",
    middle_names: null,
    last_name: "Chandra-Bose",
    full_name: "Priya Chandra-Bose",
    date_of_birth: "1985-07-02",
    ni_number: "QQ123456C",
    legal_sex: "female",
    marital_status: "cohabiting",
    nationality: "GB",
    addresses: [
      {
        primary: true,
        line1: "Flat 4",
        line2: "12 Vereker Road",
        town_city: "London",
        county: "Greater London",
        postcode: "W14 9JR",
        country: "GB",
        move_in_date: "2016-03-01",
      },
    ],
    contact_details: [
      { type: "email", value: "priya.cb@example.co.uk", primary: true },
      { type: "mobile", value: "+447700900123", primary: true },
      { type: "email", value: "priya@oldmail.example", primary: false },
    ],
  };
}

export function expectedBeacon(): CanonicalClient {
  return {
    schema_version: CANONICAL_V1_VERSION,
    id: "c0ffee7a-1e4b-2c9d-3e00-000000000001",
    title: "Mrs",
    first_name: "Priya",
    middle_names: null,
    last_name: "Chandra-Bose",
    full_name: "Priya Chandra-Bose",
    date_of_birth: "1985-07-02",
    ni_number: "QQ123456C",
    legal_sex: "female",
    marital_status: "cohabiting",
    nationality: "GB",
    addresses: [
      {
        primary: true,
        line1: "Flat 4",
        line2: "12 Vereker Road",
        town_city: "London",
        county: "Greater London",
        postcode: "W14 9JR",
        country: "GB",
        move_in_date: null,
      },
    ],
    contact_details: [
      { type: "email", value: "priya.cb@example.co.uk", primary: true },
      { type: "mobile", value: "+447700900123", primary: true },
    ],
  };
}
